default_platform :ios
skip_docs
opt_out_usage

lane :bump_version_patch do
  bump_version(part: "patch")
end

lane :bump_version do |options|
  fastlane_require 'fastlane-ext'

  UI.message "Going to bump project version"
  sync_git_tags

  raise "Invalid part, correct one is [patch|minor|major]" unless options[:part]
  cmd = "bundle exec git-version-bump " + options[:part]
  raise "Failed to patch version! cmd: '#{cmd}'" unless system(cmd)
end

lane :test do
  scan(scheme: "Demo", device: 'iPhone 11')
end

lane :test_if_needed do
  unless stopped?
    test
  end
end

def stopped?
  stop_keywords.any? do |k|
    last_git_commit[:message].to_s.downcase.include?(k)
  end
end

def stop_keywords
  ["wip", "stop"]
end
