default_platform :ios
skip_docs
opt_out_usage

lane :patch_version do 
  UI.message "going to patch version"
  cmd = "bundle exec git-version-bump patch"
  raise "Failed to patch version! Error: '#{cmd}'" unless system(cmd)
end

lane :test do
  scan(scheme: "Demo")
end

lane :test_if_needed do 
  unless stopped?
    test
  end
end

def stopped?
  stop_keywords.any? do |k|
    last_git_commit[:message].to_s.downcase.include?(k) 
  end
end

def stop_keywords
  ["wip", "stop"]
end
